- hosts: all 
  tasks:
    - name: Install docker-py
      pip:
        name: 'https://pypi.python.org/packages/source/d/docker-py/docker-py-1.1.0.tar.gz'
        state: present
        
    - name: build the image
      command: sudo docker build -t helloworldapp:ex1
      
    - name: start docker container
          docker:
            name: helloworldappimage
            image: "helloworldapp:ext1"
            state: reloaded
            publish_all_ports: yes