- hosts: all 
  tasks:
    - name: Install docker-py
      pip:
        name: 'https://pypi.python.org/packages/source/d/docker-py/docker-py-1.1.0.tar.gz'
        state: present
        
    - name: build docker image
      docker_image:
        name: helloworldapp
        source: build  
        build:         
          path: /home/deshant
      tags: ext1
      
    - name: start docker container
      docker_container:
        name: helloworldappimage
        image: "helloworldapp:ext1"
        state: reloaded
        publish_all_ports: yes